//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class place
    {
        public int id { get; set; }
        public string country_code { get; set; }
        public string postal_code { get; set; }
        public string place_name { get; set; }
        public string admin_name1 { get; set; }
        public string admin_code1 { get; set; }
        public string admin_name2 { get; set; }
        public string admin_code2 { get; set; }
        public string admin_name3 { get; set; }
        public string admin_code3 { get; set; }
        public decimal latitude { get; set; }
        public decimal longitude { get; set; }
        public byte accuracy { get; set; }
    }
}
